export interface SkillIconEntry {
  iconName: string;
  gradient: string;
  brandColor: string;
}

export const skillIconData: Record<string, SkillIconEntry> = {
  python: { iconName: 'SiPython', gradient: 'from-blue-500 to-yellow-400', brandColor: '#3776AB' },
  javascript: { iconName: 'SiJavascript', gradient: 'from-yellow-300 to-yellow-500', brandColor: '#F7DF1E' },
  typescript: { iconName: 'SiTypescript', gradient: 'from-blue-500 to-blue-700', brandColor: '#3178C6' },
  java: { iconName: 'DiJava', gradient: 'from-red-500 to-orange-500', brandColor: '#007396' },
  csharp: { iconName: 'SiSharp', gradient: 'from-gray-700 to-gray-900', brandColor: '#239120' },
  c: { iconName: 'SiC', gradient: 'from-blue-500 to-blue-700', brandColor: '#A8B9CC' },
  cplusplus: { iconName: 'SiCplusplus', gradient: 'from-blue-600 to-indigo-700', brandColor: '#00599C' },
  rust: { iconName: 'SiRust', gradient: 'from-orange-500 to-red-600', brandColor: '#DEA584' },
  go: { iconName: 'SiGo', gradient: 'from-cyan-400 to-blue-500', brandColor: '#00ADD8' },
  dart: { iconName: 'SiDart', gradient: 'from-blue-400 to-cyan-500', brandColor: '#0175C2' },
  kotlin: { iconName: 'SiKotlin', gradient: 'from-purple-500 to-orange-400', brandColor: '#7F52FF' },
  swift: { iconName: 'SiSwift', gradient: 'from-orange-400 to-red-500', brandColor: '#F05138' },
  php: { iconName: 'SiPhp', gradient: 'from-indigo-400 to-purple-600', brandColor: '#777BB4' },
  html5: { iconName: 'SiHtml5', gradient: 'from-orange-400 to-orange-600', brandColor: '#E34F26' },
  css3: { iconName: 'SiCss', gradient: 'from-blue-400 to-blue-600', brandColor: '#1572B6' },
  react: { iconName: 'SiReact', gradient: 'from-cyan-400 to-blue-500', brandColor: '#61DAFB' },
  nextdotjs: { iconName: 'SiNextdotjs', gradient: 'from-gray-600 to-gray-900', brandColor: '#FFFFFF' },
  nextjs: { iconName: 'SiNextdotjs', gradient: 'from-gray-600 to-gray-900', brandColor: '#FFFFFF' },
  vuedotjs: { iconName: 'SiVuedotjs', gradient: 'from-green-400 to-[var(--accent)]', brandColor: '#4FC08D' },
  vue: { iconName: 'SiVuedotjs', gradient: 'from-green-400 to-[var(--accent)]', brandColor: '#4FC08D' },
  angular: { iconName: 'SiAngular', gradient: 'from-red-500 to-red-700', brandColor: '#DD0031' },
  svelte: { iconName: 'SiSvelte', gradient: 'from-orange-500 to-red-500', brandColor: '#FF3E00' },
  astro: { iconName: 'SiAstro', gradient: 'from-purple-500 to-orange-500', brandColor: '#FF5D01' },
  tailwindcss: { iconName: 'SiTailwindcss', gradient: 'from-cyan-400 to-blue-500', brandColor: '#06B6D4' },
  fastapi: { iconName: 'SiFastapi', gradient: 'from-teal-400 to-[var(--accent)]', brandColor: '#05998B' },
  django: { iconName: 'SiDjango', gradient: 'from-green-700 to-green-900', brandColor: '#092E20' },
  flask: { iconName: 'SiFlask', gradient: 'from-gray-500 to-gray-800', brandColor: '#000000' },
  laravel: { iconName: 'SiLaravel', gradient: 'from-red-500 to-red-700', brandColor: '#FF2D20' },
  nodedotjs: { iconName: 'SiNodedotjs', gradient: 'from-green-500 to-green-700', brandColor: '#339933' },
  nodejs: { iconName: 'SiNodedotjs', gradient: 'from-green-500 to-green-700', brandColor: '#339933' },
  sqlite: { iconName: 'SiSqlite', gradient: 'from-sky-400 to-blue-600', brandColor: '#003B57' },
  mongodb: { iconName: 'SiMongodb', gradient: 'from-green-500 to-green-700', brandColor: '#47A248' },
  postgresql: { iconName: 'SiPostgresql', gradient: 'from-blue-500 to-indigo-600', brandColor: '#4169E1' },
  mysql: { iconName: 'SiMysql', gradient: 'from-blue-500 to-orange-500', brandColor: '#4479A1' },
  redis: { iconName: 'SiRedis', gradient: 'from-red-500 to-red-700', brandColor: '#DC382D' },
  firebase: { iconName: 'SiFirebase', gradient: 'from-yellow-400 to-orange-500', brandColor: '#FFCA28' },
  git: { iconName: 'SiGit', gradient: 'from-orange-500 to-red-600', brandColor: '#F05032' },
  docker: { iconName: 'SiDocker', gradient: 'from-blue-400 to-cyan-500', brandColor: '#2496ED' },
  linux: { iconName: 'SiLinux', gradient: 'from-yellow-400 to-yellow-600', brandColor: '#FCC624' },
  nginx: { iconName: 'SiNginx', gradient: 'from-green-500 to-green-700', brandColor: '#009639' },
  amazonwebservices: { iconName: 'FaAws', gradient: 'from-orange-400 to-yellow-500', brandColor: '#232F3E' },
  aws: { iconName: 'FaAws', gradient: 'from-orange-400 to-yellow-500', brandColor: '#232F3E' },
  googlecloud: { iconName: 'SiGooglecloud', gradient: 'from-blue-400 to-red-400', brandColor: '#4285F4' },
  vercel: { iconName: 'SiVercel', gradient: 'from-gray-600 to-gray-900', brandColor: '#000000' },
  netlify: { iconName: 'SiNetlify', gradient: 'from-teal-400 to-cyan-500', brandColor: '#00C7B7' },
  flutter: { iconName: 'SiFlutter', gradient: 'from-blue-400 to-cyan-400', brandColor: '#02569B' },
  graphql: { iconName: 'SiGraphql', gradient: 'from-pink-500 to-purple-600', brandColor: '#E10098' },
  figma: { iconName: 'SiFigma', gradient: 'from-purple-500 to-pink-500', brandColor: '#F24E1E' },
  nuxtdotjs: { iconName: 'SiNuxt', gradient: 'from-gray-700 to-gray-900', brandColor: '#00DC82' },
  bootstrap: { iconName: 'FaBootstrap', gradient: 'from-gray-700 to-gray-900', brandColor: '#7952B3' },
  vite: { iconName: 'SiVite', gradient: 'from-gray-700 to-gray-900', brandColor: '#646CFF' },
  electron: { iconName: 'SiElectron', gradient: 'from-cyan-500 to-blue-600', brandColor: '#47848F' },
  express: { iconName: 'SiExpress', gradient: 'from-gray-700 to-gray-900', brandColor: '#111111' },
  nestjs: { iconName: 'SiNestjs', gradient: 'from-gray-700 to-gray-900', brandColor: '#E0234E' },
  dotnet: { iconName: 'SiDotnet', gradient: 'from-gray-700 to-gray-900', brandColor: '#512BD4' },
  reactnative: { iconName: 'FaReact', gradient: 'from-gray-700 to-gray-900', brandColor: '#61DAFB' },
  supabase: { iconName: 'SiSupabase', gradient: 'from-gray-700 to-gray-900', brandColor: '#3ECF8E' },
  github: { iconName: 'FaGithub', gradient: 'from-gray-700 to-gray-900', brandColor: '#181717' },
  githubactions: { iconName: 'SiGithubactions', gradient: 'from-gray-700 to-gray-900', brandColor: '#2088FF' },
  postman: { iconName: 'SiPostman', gradient: 'from-gray-700 to-gray-900', brandColor: '#FF6C37' },
  amazonaws: { iconName: 'FaAws', gradient: 'from-gray-700 to-gray-900', brandColor: '#FF9900' },
  microsoftazure: { iconName: 'VscAzure', gradient: 'from-gray-700 to-gray-900', brandColor: '#0078D4' },
  digitalocean: { iconName: 'SiDigitalocean', gradient: 'from-blue-500 to-cyan-400', brandColor: '#0080FF' },
  cloudflare: { iconName: 'SiCloudflare', gradient: 'from-orange-400 to-amber-500', brandColor: '#F38020' },
  nuxt: { iconName: 'SiNuxt', gradient: 'from-gray-700 to-gray-900', brandColor: '#00DC82' },
  remix: { iconName: 'SiRemix', gradient: 'from-blue-500 to-indigo-600', brandColor: '#3992FF' },
  gatsby: { iconName: 'SiGatsby', gradient: 'from-purple-600 to-indigo-700', brandColor: '#663399' },
  mui: { iconName: 'SiMui', gradient: 'from-blue-500 to-blue-700', brandColor: '#007FFF' },
  webpack: { iconName: 'SiWebpack', gradient: 'from-blue-400 to-sky-600', brandColor: '#8DD6F9' },
  rubyonrails: { iconName: 'SiRubyonrails', gradient: 'from-red-500 to-red-700', brandColor: '#CC0000' },
  springboot: { iconName: 'SiSpringboot', gradient: 'from-green-500 to-green-700', brandColor: '#6DB33F' },
  strapi: { iconName: 'SiStrapi', gradient: 'from-indigo-500 to-purple-600', brandColor: '#4945FF' },
  fastify: { iconName: 'SiFastify', gradient: 'from-gray-600 to-gray-800', brandColor: '#000000' },
  ionic: { iconName: 'SiIonic', gradient: 'from-blue-400 to-indigo-500', brandColor: '#3880FF' },
  elasticsearch: { iconName: 'SiElasticsearch', gradient: 'from-yellow-400 to-amber-500', brandColor: '#005571' },
  mariadb: { iconName: 'SiMariadb', gradient: 'from-blue-500 to-indigo-600', brandColor: '#003545' },
  planetscale: { iconName: 'SiPlanetscale', gradient: 'from-purple-500 to-pink-500', brandColor: '#000000' },
  prisma: { iconName: 'SiPrisma', gradient: 'from-gray-700 to-gray-900', brandColor: '#2D3748' },
  kubernetes: { iconName: 'SiKubernetes', gradient: 'from-blue-500 to-blue-700', brandColor: '#326CE5' },
  terraform: { iconName: 'SiTerraform', gradient: 'from-purple-600 to-indigo-700', brandColor: '#7B42BC' },
  gitlab: { iconName: 'SiGitlab', gradient: 'from-orange-500 to-red-600', brandColor: '#FC6D26' },
  bitbucket: { iconName: 'SiBitbucket', gradient: 'from-blue-500 to-blue-700', brandColor: '#0052CC' },
  jenkins: { iconName: 'SiJenkins', gradient: 'from-red-400 to-red-600', brandColor: '#D33833' },
  circleci: { iconName: 'SiCircleci', gradient: 'from-gray-600 to-gray-800', brandColor: '#343434' },
  jira: { iconName: 'SiJira', gradient: 'from-blue-500 to-indigo-600', brandColor: '#0052CC' },
  grafana: { iconName: 'SiGrafana', gradient: 'from-orange-400 to-amber-500', brandColor: '#F46800' },
  prometheus: { iconName: 'SiPrometheus', gradient: 'from-orange-500 to-red-500', brandColor: '#E6522C' },
  n8n: { iconName: 'SiN8N', gradient: 'from-rose-500 to-pink-600', brandColor: '#EA4B71' },
  zapier: { iconName: 'SiZapier', gradient: 'from-orange-400 to-amber-500', brandColor: '#FF4A00' },
  ruby: { iconName: 'SiRuby', gradient: 'from-red-500 to-red-700', brandColor: '#CC342D' },
  scala: { iconName: 'SiScala', gradient: 'from-red-500 to-red-700', brandColor: '#DC322F' },
  lua: { iconName: 'SiLua', gradient: 'from-blue-400 to-blue-600', brandColor: '#000080' },
  r: { iconName: 'SiR', gradient: 'from-blue-500 to-indigo-600', brandColor: '#276DC3' },
  perl: { iconName: 'SiPerl', gradient: 'from-blue-400 to-cyan-500', brandColor: '#39457E' },
  haskell: { iconName: 'SiHaskell', gradient: 'from-purple-500 to-indigo-600', brandColor: '#5D4F85' },
  elixir: { iconName: 'SiElixir', gradient: 'from-purple-500 to-pink-500', brandColor: '#6E4A7E' },
  zig: { iconName: 'SiZig', gradient: 'from-amber-400 to-yellow-500', brandColor: '#F7A41D' },
  pytorch: { iconName: 'SiPytorch', gradient: 'from-red-500 to-orange-500', brandColor: '#EE4C2C' },
  tensorflow: { iconName: 'SiTensorflow', gradient: 'from-orange-500 to-amber-500', brandColor: '#FF6F00' },
  numpy: { iconName: 'SiNumpy', gradient: 'from-blue-600 to-indigo-700', brandColor: '#013243' },
  pandas: { iconName: 'SiPandas', gradient: 'from-indigo-500 to-purple-600', brandColor: '#150458' },
  scikitlearn: { iconName: 'SiScikitlearn', gradient: 'from-orange-400 to-red-500', brandColor: '#F0923B' },
  opencv: { iconName: 'SiOpencv', gradient: 'from-green-500 to-blue-500', brandColor: '#5C3EE8' },
  jupyter: { iconName: 'SiJupyter', gradient: 'from-orange-400 to-red-500', brandColor: '#F37626' },
  poetry: { iconName: 'SiPoetry', gradient: 'from-sky-400 to-blue-500', brandColor: '#60A6E0' },
  googlegemini: { iconName: 'SiGooglegemini', gradient: 'from-blue-400 to-indigo-500', brandColor: '#1C7BF1' },
  anthropic: { iconName: 'SiClaude', gradient: 'from-amber-300 to-orange-400', brandColor: '#D4A574' },
  huggingface: { iconName: 'SiHuggingface', gradient: 'from-yellow-400 to-amber-500', brandColor: '#FFD21E' },
  langchain: { iconName: 'SiLangchain', gradient: 'from-teal-500 to-green-600', brandColor: '#1C3C3C' },
  openrouter: { iconName: 'SiOpenrouter', gradient: 'from-indigo-500 to-purple-600', brandColor: '#6366F1' },
};

export const fallbackEntry: SkillIconEntry = {
  iconName: 'SiSimpleicons',
  gradient: 'from-gray-500 to-gray-700',
  brandColor: '#FFFFFF',
};

export const nameToSlug: Record<string, string> = {
  'html5': 'html5', 'css3': 'css3', 'javascript': 'javascript', 'typescript': 'typescript',
  'python': 'python', 'java': 'java', 'c#': 'csharp', 'csharp': 'csharp',
  'go': 'go', 'kotlin': 'kotlin', 'swift': 'swift', 'dart': 'dart', 'php': 'php',
  'react': 'react', 'next.js': 'nextdotjs', 'nextdotjs': 'nextdotjs', 'nextjs': 'nextdotjs',
  'vue.js': 'vuedotjs', 'vue': 'vuedotjs', 'nuxt.js': 'nuxtdotjs', 'nuxt': 'nuxtdotjs',
  'angular': 'angular', 'svelte': 'svelte', 'astro': 'astro',
  'tailwind css': 'tailwindcss', 'tailwind': 'tailwindcss', 'tailwindcss': 'tailwindcss',
  'bootstrap': 'bootstrap', 'vite': 'vite',
  'node.js': 'nodedotjs', 'nodejs': 'nodedotjs', 'fastapi': 'fastapi',
  'django': 'django', 'flask': 'flask', 'laravel': 'laravel', 'express': 'express',
  'nestjs': 'nestjs', 'graphql': 'graphql', '.net': 'dotnet', 'dotnet': 'dotnet',
  'flutter': 'flutter', 'react native': 'reactnative',
  'postgresql': 'postgresql', 'mysql': 'mysql', 'sqlite': 'sqlite',
  'mongodb': 'mongodb', 'redis': 'redis', 'supabase': 'supabase', 'firebase': 'firebase',
  'docker': 'docker', 'git': 'git', 'github': 'github', 'electron': 'electron',
  'github actions': 'githubactions', 'linux': 'linux',
  'vercel': 'vercel', 'netlify': 'netlify', 'figma': 'figma', 'postman': 'postman',
  'aws': 'aws', 'amazon web services': 'aws', 'azure': 'microsoftazure',
  'google cloud': 'googlecloud', 'remix': 'remix', 'gatsby': 'gatsby',
  'mui': 'mui', 'material ui': 'mui', 'webpack': 'webpack', 'rails': 'rubyonrails',
  'ruby on rails': 'rubyonrails', 'spring boot': 'springboot', 'strapi': 'strapi',
  'fastify': 'fastify', 'ionic': 'ionic', 'elasticsearch': 'elasticsearch',
  'mariadb': 'mariadb', 'planetscale': 'planetscale', 'prisma': 'prisma',
  'kubernetes': 'kubernetes', 'k8s': 'kubernetes', 'terraform': 'terraform',
  'gitlab': 'gitlab', 'bitbucket': 'bitbucket', 'jenkins': 'jenkins',
  'circleci': 'circleci', 'jira': 'jira', 'grafana': 'grafana',
  'prometheus': 'prometheus', 'n8n': 'n8n', 'zapier': 'zapier',
  'digitalocean': 'digitalocean', 'cloudflare': 'cloudflare',
  'ruby': 'ruby', 'scala': 'scala', 'lua': 'lua', 'r': 'r', 'perl': 'perl',
  'haskell': 'haskell', 'elixir': 'elixir', 'zig': 'zig',
  'pytorch': 'pytorch', 'tensorflow': 'tensorflow', 'numpy': 'numpy',
  'pandas': 'pandas', 'scikit-learn': 'scikitlearn', 'scikitlearn': 'scikitlearn',
  'opencv': 'opencv', 'jupyter': 'jupyter', 'poetry': 'poetry',
  'google gemini': 'googlegemini', 'gemini': 'googlegemini',
  'anthropic': 'anthropic', 'claude': 'anthropic',
  'hugging face': 'huggingface', 'huggingface': 'huggingface',
  'langchain': 'langchain', 'openrouter': 'openrouter', 'open router': 'openrouter',
};

export function getSkillIconData(slug: string): SkillIconEntry {
  const key = slug.toLowerCase().trim();
  const resolved = nameToSlug[key] || key;
  return skillIconData[resolved] || skillIconData[key] || fallbackEntry;
}
